name: cd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cd:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up node env
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Generate
      run: yarn generate
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
